#!/bin/sh
BRANCH=`git rev-parse --abbrev-ref HEAD`

if [[ "$BRANCH" == "master" || "$BRANCH" == "release"* ]]; then
	echo "You are on branch $BRANCH. Are you sure you want to commit to this branch?"
	echo "If so, commit with -n to bypass this pre-commit hook."
	exit 1
fi

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "html$")
if [[ "$STAGED_FILES" = "" ]]; then
    exit 0
fi

PASS=true

for FILE in $STAGED_FILES
do
    if [[ "$FILE" =~ .*bower_components.* ]]; then
        continue
    fi
    jshint --extract=auto "$FILE"

    if [[ "$?" == 0 ]]; then
        echo "\t\033[32mJSHint Passed: $FILE\033[0m"
    else
        echo "\t\033[41mJSHint Failed: $FILE\033[0m"
        PASS=false
    fi
done
if [[ ! "$PASS" ]]; then
    exit 1
fi
